### ISSUE TITLE
Axel 

### ISSUE THREAD

**Issue by eleninikou** [chas-academy/Gold-api#34]
https://github.com/chas-academy/Gold-api/blob/44ba69030eb74847fc289269624a86f65d82d01e/src/routes/index.js#L6-L62

**Comment by axelolsson** [comment]
Looks good, here are some comments:

---

1. Split routes into files and import controllers as needed into those route files (see here https://expressjs.com/en/guide/routing.html#express-router)
2. Tests :)
3. Remove. Dead. Code.
4. Instead of commenting the controller methods, document the API using http://apidocjs.com/ or https://github.com/swagger-api/swagger-node - future developers will thank you.
5. Add *helmet* as a dependency if you haven't already and a logger like *morgan*
6. Think about how you will deliver this to production to the client, where will it be hosted, who will maintain it?
7. Backups! Depending on where this will live the database will need to be backed up regularly
